### ISSUE TITLE
[UC]Manage course file

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#9] opened 2015-08-03 03:00 UTC

**Comment by jbaltazar** [comment] 2015-08-04 09:08
**DEV20150804: DEV Tested. Error in TEST Server.**
- Can't Download any file where the File Path is being redirected to "localhost:3000" instead in "lmstest.nucloudglobal.net:3000".

**Screenshot from TEST Server:[Status: Not-Working]**
![scr_1](https://cloud.githubusercontent.com/assets/7844693/9057082/f1e87c5e-3ac9-11e5-8c20-ce8644f9763e.png)
![scr_2](https://cloud.githubusercontent.com/assets/7844693/9057088/f91a7478-3ac9-11e5-9df2-6fb68545a7bc.png)
![scr_3](https://cloud.githubusercontent.com/assets/7844693/9057092/00649c5e-3aca-11e5-85a6-9018764210c0.png)


**Solution:**
- Need to change the "test", "development" and "production" domain under domain.yml so that user can download any files.

**Code Location:** [https://github.com/nucloudglobal/lms/blob/dev/config/domain.yml.example](https://github.com/nucloudglobal/lms/blob/dev/config/domain.yml.example)

**Screenshot from my local Dev Server:[Status: Working]**
![working_course_file_management](https://cloud.githubusercontent.com/assets/7844693/9057094/07eece36-3aca-11e5-9374-e7da76abe967.png)


**Concern:**
- Currently I don't have access in TEST server.
@apetitnucloud Can you change this so that @nucloud-agutierrez  can start to test this UC or I'm going to change this in my local and will push the changes to [DEV](https://github.com/nucloudglobal/lms/tree/dev) branch and you will pull this changes to TEST Server?

Thank you

**Comment by lance-huang-nucloudglobal** [comment] 2015-08-05 04:23
@jbaltazar 
I believe it has not reach TEST ready if there's defect found by DEV but not fixed.

**Comment by jbaltazar** [comment] 2015-08-05 07:13
@lance-huang-nucloudglobal 
Technically speaking, yes. where the issue is not yet fix in the TEST Server, But we can assume that after @apetitnucloud update the solution that I mention in my previous message. Everything is ok and ready to test.

**Comment by jbaltazar** [comment] 2015-08-07 01:07
@apetitnucloud I just want to follow up my concern on my previous message. Joy might start to test this one under TEST Server when [http://lmstest.nucloudglobal.net:3000](http://lmstest.nucloudglobal.net:3000) or [http://5.196.18.110:3000/](http://5.196.18.110:3000/) is already accessible.

CC @lance-huang-nucloudglobal

**Comment by apetitnucloud** [comment] 2015-08-12 03:05
@jbaltazar @lance-huang-nucloudglobal  this should happen since the deployment script take care of all the .yml files in the shared folder please see this link if you are curious about ansible script https://github.com/apetitnucloud/ansible_script_for_canvas_production.
But this server is temporary test server so I will just correct it manually, i will tell you when it will be done.

**Comment by lance-huang-nucloudglobal** [comment] 2015-09-21 03:35
@apetitnucloud @jbaltazar 
May I know when this UC can be TEST ready, from the function perspective, it is a LMS default function.

**Comment by lance-huang-nucloudglobal** [comment] 2015-09-25 04:13
1.Create academic manager at http://lmssqa.nucloudglobal.net/accounts/4/permissions
2.Create user eg_academic_manager@eg.com and add it as the academic manager of the sub-account http://lmssqa.nucloudglobal.net/accounts/4/settings
3.login as eg_academic_manager@eg.com 

TEST result

------
4.User will see all courses in the global-navigation
PA - saw the sub-account

5.User click one of the course to step into it
N/A (not a test point) http://lmssqa.nucloudglobal.net/courses/2
User click on [Files] on course-navigation; 
N/A (not a test point) http://lmssqa.nucloudglobal.net/courses/2/files

6.User can CRUD files, other common action can be done on files
PA C=upload, R=download, U=rename D=delete
	Add folder
PA
	Move file
PA
	Preview file
PA
	Restrict file – publish, unpublish, restrict access
Login as student http://lmssqa.nucloudglobal.net/accounts/1/users/19 (masquerade)
Publish = PA
unpublish = PA
restrict access - only available as link = PA 
link = http://lmssqa.nucloudglobal.net/files/28/download?download_frd=1 
restrict access - schedule availability = PA

More details about how to restrict file, pls see http://guides.instructure.com/m/4152/l/41391-how-do-i-restrict-files-and-folders-to-students-in-canvas

**Comment by nucloud-agutierrez** [comment] 2015-11-03 06:55
QA20151103: QA tested. Reopened.

Steps to Replicate
1. Login as Academic Manager (sqamanager@domain.com)
- User will see all courses in the global-navigation (saw the sub account)
2. User click one of the course to step into it
3. User click on [Files] on course-navigation
4. User can CRUD files, other common action can be done on files
C=upload, R=download, U=rename D=delete

Actual Result:
- User is not able to upload a file. 

![manage course file_failed](https://cloud.githubusercontent.com/assets/8049330/10902566/d6df90c4-823a-11e5-8166-227fe3316a1d.png)

**Comment by nucloud-agutierrez** [comment] 2015-11-04 09:27
QA20151104: QA tested. Fixed in TEST Environment.

Steps to Replicate
1. Login as Academic Manager (sqamanager@domain.com).
User will see all courses in the global-navigation (saw the sub account)
2. User click one of the course to step into it (SQA Course 1)
3. User click on [Files] on course-navigation
4. User can CRUD files, other common action can be done on files
C=upload, R=download, U=rename D=delete

**Comment by nucloud-agutierrez** [comment] 2016-01-27 10:31
QA20160127: QA tested. Fixed in PROD Environment.

Steps to Replicate
1. Login as Academic Manager (sqamanager@domain.com).
User will see all courses in the global-navigation (saw the sub account)
2. User click one of the course to step into it (SQA Course 1)
3. User click on [Files] on course-navigation
4. User can CRUD files, other common action can be done on files
C=upload, R=download, U=rename D=delete
5. Login as a student (sqastudent@domain.com)
Publish - PASSED
Unpublish - PASSED
Restrict Access - PASSED
link: https://lms.condenastcenter.com.cn/courses/2/files/folder/?preview=1
Restrick Access - Schedule Availabilty - PASSED

**Closed** 2016-01-29 03:00 UTC
Labels: Proc.DEV, PROD sqa verified, S.29, Sprint 3, TEST sqa verified, UAT sqa verified
